### ISSUE TITLE
Feature Request - Curved inner corners

### ISSUE THREAD

**Issue by valdisd** [Alex9779/IKEA-Samla-Inserts#11]
It would be great if there would be an option to add the possibility to have curved (rounded) inner corners (or probably one of them) so it would be easier to get things out of the compartments.
Unfortunately, I do not have any familiarity with this, so I cannot help with a PR. But would this be something you could do?
I could tip you a coffee or a beer though.

**Comment by Alex9779** [comment]
Nice idea, I see what I can do...

**Comment by Alex9779** [comment]
One question to this, do you mean curves between the side walls or between bottom and a side wall? Maybe both?

**Comment by valdisd** [comment]
Between the bottom and sidewall. I tried to add one in Tinkercad. Here is the image so you get a better insight - https://ibb.co/Ks2Byqk It can of course be smoother did manage to do that.
One round edge is all needed. No need to put them on every side.

**Comment by Alex9779** [comment]
Got it, I already tried changing the grid algorithm but will take some time, currently the grid is crating the walls, the idea is to change to a rounded cube algorithm and create the empty spaces as rounded cubes and do a difference instead of the intersection, have problems with proper spacing and side walls then because of all the measures increasing with height...

**Comment by valdisd** [comment]
Any updates? I already printed some and for my purpose, the rounded edges are really necessary. I also printed one of my own attempts of adding them, but that was a very time-consuming process and needs to be done for each different configuration.

**Comment by Alex9779** [comment]
Sorry other priorities and the way you want it is not easy to solve because of the structure the grid and the bottom is created, also my attempt to use a rounded cube does not work for this because you can't scales that cube in upper direction which is needed to the the widening.
I am thinking about creating the fillets with an extra module and then move them into place and limit that to inner walls which are straight to the too top not like the side walls, but I have no quick solution...

**Comment by Alex9779** [comment]
I just published a draft here: https://github.com/Alex9779/IKEA-Samla-Inserts/tree/11-curved-inner-corner
Look for the "Fillets" option and activate it...

**Comment by Alex9779** [comment]
@valdisd did you see my last post? Did you have a chance to check it out?

**Comment by Alex9779** [comment]
Merged to master, if there are any problems open a new issue.
