### ISSUE TITLE
DXF format

### ISSUE THREAD

**Issue by gute1** [Alex9779/IKEA-Samla-Inserts#3]
Hi,
I want to migrate your work to other software like Solidworks. it is difficult to translate the  scad file. can you add a DXF file of the bottom, top and side cut of the volume?

**Comment by Alex9779** [comment]
Hello,
sorry I don't have such a file. All I could do but that you can do yourself is get the measures from the file and redesign it in a sketch in SWx, shouldn't be that hard.
But honestly I see no point in doing so because SWx is much more limited generating dynamic models based on calculations.
With about an hour of work you can generate the internal volume but then you have to cut it and add the grid.
Why do you want to model it in SWx?

**Comment by christiandufner** [comment]
Hey, i solved it and thx, i had a moment of abstraction why ive chosen the wrong file! Thx 4 your support and the great design.
Im going to upload my make! 
Wanted to tip you but there i wasnt able to.
Best greetings, Christian

**Comment by Alex9779** [comment]
Hi,

cool you got what you wanted… Tips appreciated, paypal.me/alex9779 <http://paypal.me/alex9779> should work but that’s also on Thingiverse so no idea…

Regards,
Alexander
